### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by PseudoDistant** [MajickTek/MiniCraftLauncher#1]
Mainly just here because I forgor, I'll try to contribute later.

The use of JVM arguments might help.
`java -Dfabric.skipMcProvider=true -Dfabric.gameJarPath=path/to/minicraft.jar -cp path/to/fabric-loader-0.13.0.jar:path/to/MinicraftGameProvider.jar:fabric/dependency/dir/* net.fabricmc.loader.launch.knot.KnotClient`

**Comment by MajickTek** [comment]
Currently I am implementing XML support (you can see in the `xml-refactor` branch). This will be used for the index (version) files and will be a lot more flexible.

Afterwards, adding support for jars with a lot of extra parts like fabric should be a breeze

**Comment by MajickTek** [comment]
Update: Now that a proper XML format is in place, some cleaning up of the code needs to be done (one of which is a restructuring of the UI for visual clarity). Then Fabric can be implemented

**Comment by MajickTek** [comment]
Update: My next plan is to do an overhaul of the main UI, perhaps using a JTree structure instead of the JList model which was directly ripped from my ZoomManager project (https://github.com/MajickTek/ZoomManager).

This will let me organize the versions by game by placing them into "folders"

After that it will be infinitely easier to expand functionality and brings me one step closer to having Fabric support

**Comment by MajickTek** [comment]
Update: Using the results of #4 , it is now actually possible to add support for other launch systems including the internal asm system im using for testing

**Comment by MajickTek** [comment]
I am in the final stage of adding Fabric support. Once I find the minimum amount of dependencies, i can find a way to package everything with the launcher and it will be good to go.

**Comment by MajickTek** [comment]
And, it's "done". Usable. Pushing in the next release and closing.
